# LIST - A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements
L=[1,2,3,4,5,6,7,8,9,10]
print(L)
x=[[1,2,3],['a','b','c']]  #list in list
print(x)

# LIST SLICING - list(startindex : endindex : index jump)
# Ex-1
L=[23,34,84,82,23,9,28]
print(L[::])  #prints the exact list
print(L[0: :1])  #positive indexing
print(L[-7:-2:2])  #negative indexing
print(L[::2])

# Ex-2 - A reversed list can be generated by using a negative integer as the IndexJump argument. Leaving the Initial and End as blank. We need to choose the Initial and End values according to a reversed list if the IndexJump value is negative
V = ['hai',4,'you',2]
print(V[::])
print(V[::-1])
print(V[::-3])

# LIST OPERATIONS

lst = [1,2,3,4,5]
print(lst)

# 1. APPEND() - Adds an element to the end of the list
lst.append(6)  
print('append list is ',lst)

# 2. EXTEND() - Adds more than one element to the end of the list
lst.extend([7,8,9])  
print('extend list is ',lst)

# 3. INSERT() - adds element in between the list 
lst.insert(3,30) 
        # here adds 30 at 3rd index
print('updated list is ',lst)

# 4. REMOVE() - removes an element from the list
lst.remove(30)  
print('updated list is ',lst)

# 5. POP() - removes the last element from the list
lst.pop()  
print('list after pop() ',lst)

# 6. SLICE() - prints sliced list
print('slicing list is ',lst[2:7:1])  

# 7. REVERSE() - shows the list in reverse order  
#lst.reverse()  
#print(lst)

# 8. LEN(),MAX(),MIN() - gives the length,max & min value of the list
print(len(lst))  
print(max(lst))  
print(min(lst)) 

# 9. COUNT() - counts the no. of times an element occurs
lst.extend([9,10,11,12,12,12])
print(lst)
print(lst.count(12))  

# 10. CONCATENATE() - concatenates(combines) 2 lists
#m=lst+lst
#print('new list is ', m) 

# 11. INDEX() - Gives index number of an element in the list
print('index of 12 is ', lst.index(11))  

# 12. MULTIPLY() - Multiplies the occurrence of elements in a list
a=[1,2,3]
b=a*3
print(b) 

# 13. SORT() -  sorts the list in ascending order
x=[23,74,11,98,54,87]
x.sort()        
print('sorted list is ',x) 

# 14. CLEAR() - clears all elements in the list
y=[1,2,3,4,5]
y.clear()       
print(y)

# 15. COPY() -  returns copy of the list
a=['a','b','c']
b=a.copy()  
print(a)
print(b)










